files: ^src/

repos:
-   repo: local
    hooks:
      - id: isort
        name: Run isort
        entry: isort
        language: python 
        types: [python]
        args:
          [
            "--profile",
            "black",
          ]     

      - id: black
        name: Run black
        entry: black
        types: [python]
        language: python 
        args:
          [
            "--config=pyproject.toml",
          ]

      - id: flake8
        name: Run flake8
        entry: flake8
        language: python 
        args:
          [
            "--config=setup.cfg",
          ]

      - id: pylint
        name: pylint
        entry: pylint
        language: python
        args:
          [
            "--rcfile=pyproject.toml",
            "-rn", # Only display messages
          ]